import {
  FileImage,
  Layers,
  Scissors,
  RotateCw,
  Trash2,
  FileOutput,
  FilePlus,
  Droplets,
  Hash,
  PenTool,
  Image,
  Archive,
  PenLine,
  Highlighter,
  Lock,
  Unlock,
  MessageSquare,
  FileText,
  Presentation,
  FileSpreadsheet,
  ScanLine,
  CreditCard,
  Receipt,
  ContactRound,
  ScanText,
  Sparkles,
  Eraser,
} from 'lucide-react'
import type { ToolDefinition } from '@/types/tool'

/**
 * Single source of truth for every tool in the app — drives both the nav
 * and the router. One real route per tool (no catch-all) so every tool is
 * deep-linkable and SEO-indexable, even while "coming soon".
 */
export const TOOLS_REGISTRY: ToolDefinition[] = [
  {
    slug: 'image-to-pdf',
    title: 'Image to PDF',
    description: 'Turn photos and scans into a pixel-perfect, lossless PDF.',
    icon: FileImage,
    category: 'convert',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDFs into a single document.',
    icon: Layers,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF',
    description: 'Break a PDF apart into standalone files.',
    icon: Scissors,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Fix sideways or upside-down pages.',
    icon: RotateCw,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'delete-pages',
    title: 'Delete Pages',
    description: 'Remove unwanted pages from a PDF.',
    icon: Trash2,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'extract-pages',
    title: 'Extract Pages',
    description: 'Pull specific pages out into a new PDF.',
    icon: FileOutput,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'insert-blank-page',
    title: 'Insert Blank Page',
    description: 'Add a blank page anywhere in a PDF.',
    icon: FilePlus,
    category: 'organize',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'watermark-pdf',
    title: 'Watermark PDF',
    description: 'Stamp text or a logo across every page.',
    icon: Droplets,
    category: 'edit',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'add-page-numbers',
    title: 'Add Page Numbers',
    description: 'Number the pages of an existing PDF.',
    icon: Hash,
    category: 'edit',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Drop a signature onto any page.',
    icon: PenTool,
    category: 'security',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Export every page as a high-resolution JPG.',
    icon: Image,
    category: 'convert',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'pdf-to-png',
    title: 'PDF to PNG',
    description: 'Export every page as a lossless PNG.',
    icon: Image,
    category: 'convert',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'pdf-to-webp',
    title: 'PDF to WEBP',
    description: 'Export every page as a compact WEBP image.',
    icon: Image,
    category: 'convert',
    status: 'live',
    backendNeed: 'client',
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Shrink file size while keeping pages sharp.',
    icon: Archive,
    category: 'organize',
    status: 'live',
    backendNeed: 'moderate',
  },
  {
    slug: 'draw-on-pdf',
    title: 'Draw on PDF',
    description: 'Freehand sketch directly on a page.',
    icon: PenLine,
    category: 'edit',
    status: 'live',
    backendNeed: 'moderate',
  },
  {
    slug: 'highlight-pdf',
    title: 'Highlight PDF',
    description: 'Mark up passages that matter.',
    icon: Highlighter,
    category: 'edit',
    status: 'live',
    backendNeed: 'moderate',
  },
  {
    slug: 'lock-pdf',
    title: 'Lock PDF',
    description: 'Protect a PDF with a password.',
    icon: Lock,
    category: 'security',
    status: 'coming-soon',
    backendNeed: 'library',
    followUpNote: "pdf-lib has no encryption support — needs a new library.",
  },
  {
    slug: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove a password from a PDF.',
    icon: Unlock,
    category: 'security',
    status: 'coming-soon',
    backendNeed: 'library',
    followUpNote: "pdf-lib has no encryption support — needs a new library.",
  },
  {
    slug: 'annotate-pdf',
    title: 'Annotate PDF',
    description: 'Add sticky notes and comments to a page.',
    icon: MessageSquare,
    category: 'edit',
    status: 'live',
    backendNeed: 'moderate',
  },
  {
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert .docx documents into PDF.',
    icon: FileText,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert a PDF into an editable .docx.',
    icon: FileText,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'ppt-to-pdf',
    title: 'PPT to PDF',
    description: 'Convert slide decks into PDF.',
    icon: Presentation,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'pdf-to-ppt',
    title: 'PDF to PPT',
    description: 'Convert a PDF into editable slides.',
    icon: Presentation,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert spreadsheets into PDF.',
    icon: FileSpreadsheet,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Convert a PDF into an editable spreadsheet.',
    icon: FileSpreadsheet,
    category: 'convert',
    status: 'coming-soon',
    backendNeed: 'backend',
    followUpNote: 'Runs on a LibreOffice-powered Cloud Run service — deploy services/converter to go live.',
  },
  {
    slug: 'document-scanner',
    title: 'Document Scanner',
    description: 'Capture and clean up paper documents with your camera.',
    icon: ScanLine,
    category: 'scan',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
  {
    slug: 'id-scanner',
    title: 'ID Card Scanner',
    description: 'Scan and crop ID cards precisely.',
    icon: CreditCard,
    category: 'scan',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
  {
    slug: 'receipt-scanner',
    title: 'Receipt Scanner',
    description: 'Digitize receipts for expense tracking.',
    icon: Receipt,
    category: 'scan',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
  {
    slug: 'business-card-scanner',
    title: 'Business Card Scanner',
    description: 'Turn a business card photo into a clean scan.',
    icon: ContactRound,
    category: 'scan',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
  {
    slug: 'ocr',
    title: 'OCR Text Recognition',
    description: 'Pull selectable, searchable text out of any scan.',
    icon: ScanText,
    category: 'ai',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
  {
    slug: 'ai-enhance',
    title: 'AI Enhance',
    description: 'Automatically sharpen and clean up scanned pages.',
    icon: Sparkles,
    category: 'ai',
    status: 'coming-soon',
    backendNeed: 'backend',
  },
  {
    slug: 'background-removal',
    title: 'Background Removal',
    description: 'Cut a subject out from its background.',
    icon: Eraser,
    category: 'ai',
    status: 'coming-soon',
    backendNeed: 'undecided',
  },
]

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find((tool) => tool.slug === slug)
}

export const LIVE_TOOLS = TOOLS_REGISTRY.filter((tool) => tool.status === 'live')
export const COMING_SOON_TOOLS = TOOLS_REGISTRY.filter((tool) => tool.status === 'coming-soon')

export const TOOL_CATEGORY_LABELS: Record<ToolDefinition['category'], string> = {
  convert: 'Convert',
  organize: 'Organize',
  edit: 'Edit & Mark Up',
  security: 'Security & Signing',
  scan: 'Scan',
  ai: 'AI (Coming Soon)',
}
